# -*- coding: utf-8 -*-
"""Water_jugs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ToorOYjEiZdnbiPHp4a35fh3gFZ2jc5
"""

from collections import deque
def game(con1 : int, con2 : int, goal : int):
  start = (0, 0)
  visited = set()
  queue = deque([(start, [start])])
  while queue:
    (x, y), path = queue.popleft()
    if x == goal or y == goal:
      print("Goal reached:", (x, y))
      print("Path:", path)
      return
    if (x, y) in visited:
      continue
    visited.add((x, y))

    actions = [
        (con1, y),
        (x, con2),
        (0, y),
        (x, 0),
        (x + min(y, con1 - x), y - min(y, con1 - x)),
        (x - min(x, con2 - y), y + min(x, con2 - y))
    ]
    for a in actions:
      if 0 <= a[0] <= con1 and 0 <= a[1] <= con2 and a not in visited:
        queue.append((a, path + [a]))

con1 = int(input("Enter the first container: "))
con2 = int(input("Enter the second container: "))
goal = int(input("Enter the goal:"))
game(con1, con2, goal)